version: "3"

services:
  postgres:
    image: postgres:10.1-alpine
    # ports:
    #   - "5432:5432"
    environment:
      # - "TZ=Asia/Bangkok"
      - "TZ=Etc/UTC"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.e2e
    env_file:
      - .env.test
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    ports:
      - 3000:3000
